version: '3.8'

services:
  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fusion
    ports:
      - "${APP_PORT}:3000"
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - APP_PORT=${APP_PORT}
      - MONGO_URL_ATLAS_DEVELOPMENT=${MONGO_URL_ATLAS_DEVELOPMENT}
      - MONGO_URL_ATLAS_PRODUCTION=${MONGO_URL_ATLAS_PRODUCTION}
    env_file:
      - .env
