version: '3.8'

services:
  postgres:
    container_name: team-manager-api
    image: postgres:16-alpine
    env_file:
      - .env
    volumes:
      - ./data/pg:/data/postgres
    ports:
      - 5432:5432
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
volumes:
  postgres:
